// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYQRflsQHrFZ3i60fe4a05PRW3F2RKWfQ',
    appId: '1:709231411062:web:95bb71a4207dd35b52c457',
    messagingSenderId: '709231411062',
    projectId: 'my-pb-tp',
    authDomain: 'my-pb-tp.firebaseapp.com',
    storageBucket: 'my-pb-tp.firebasestorage.app',
    measurementId: 'G-03GXCQZRF4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMcvOChYxD7dJEzWF9xyBFLOnaQ_WuoVY',
    appId: '1:709231411062:android:59db738d7417836e52c457',
    messagingSenderId: '709231411062',
    projectId: 'my-pb-tp',
    storageBucket: 'my-pb-tp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzhMLO_r3SXkV5h6IFqJq1RK_XZy9v56I',
    appId: '1:709231411062:ios:daa7ef7298a33c7c52c457',
    messagingSenderId: '709231411062',
    projectId: 'my-pb-tp',
    storageBucket: 'my-pb-tp.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzhMLO_r3SXkV5h6IFqJq1RK_XZy9v56I',
    appId: '1:709231411062:ios:daa7ef7298a33c7c52c457',
    messagingSenderId: '709231411062',
    projectId: 'my-pb-tp',
    storageBucket: 'my-pb-tp.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYQRflsQHrFZ3i60fe4a05PRW3F2RKWfQ',
    appId: '1:709231411062:web:6315322c01d1d1e452c457',
    messagingSenderId: '709231411062',
    projectId: 'my-pb-tp',
    authDomain: 'my-pb-tp.firebaseapp.com',
    storageBucket: 'my-pb-tp.firebasestorage.app',
    measurementId: 'G-YZVKCFRRM6',
  );
}
